// packages/vue/src/components/Root.vue
<template>
  <div>
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted } from 'vue';
import type { TocContext, TocOptions } from '../types';
import { useTocScroll } from '../composables/useTocScroll';

const props = defineProps<{
  options?: TocOptions;
}>();

const toc = inject<TocContext>('toc');
if (!toc) throw new Error('Root must be used within Toc component');

const { activeId } = toc;

onMounted(() => {
  useTocScroll(activeId, props.options);
});
</script>

// packages/svelte/src/components/Root.svelte
<script lang="ts">
  import { getContext, onMount } from 'svelte';
  import type { TocContext, TocOptions } from '../types';
  import { useTocScroll } from '../lib/useTocScroll';

  export let options: TocOptions = {};

  const toc = getContext<TocContext>('toc');
  if (!toc) throw new Error('Root must be used within Toc component');

  const { activeId } = toc;

  let currentActiveId: string | null = null;
  activeId.subscribe(value => {
    currentActiveId = value;
    useTocScroll(value, options);
  });
</script>

<div>
  <slot></slot>
</div>
