// packages/react/src/components/section.tsx
import { createContext, forwardRef, useContext, useEffect, useId } from 'react';
import type { TocSectionContextValue, TocSectionData } from '../types';
import { useTocContext } from './root';
import { Slot } from './slot';

const TocSectionContext = createContext<TocSectionContextValue>({
  id: null,
  level: 0,
});

export interface TocSectionProps {
  title: string;
  metadata?: Record<string, unknown>;
  children?: React.ReactNode;
}

export const TocSection = forwardRef<HTMLElement, TocSectionProps>(
  (props, ref) => {
    const { title, metadata, children } = props;
    const id = useId();
    const { registerSection, unregisterSection } = useTocContext();
    const parentContext = useContext(TocSectionContext);
    const level = parentContext.level + 1;

    useEffect(() => {
      const section: TocSectionData = {
        id,
        title,
        level,
        parentId: parentContext.id,
        metadata,
      };
      registerSection(section);
      return () => unregisterSection(id);
    }, [
      id,
      title,
      level,
      parentContext.id,
      metadata,
      registerSection,
      unregisterSection,
    ]);

    const contextValue: TocSectionContextValue = {
      id,
      level,
    };

    return (
      <TocSectionContext.Provider value={contextValue}>
        <Slot ref={ref} data-toc-id={id}>
          {children}
        </Slot>
      </TocSectionContext.Provider>
    );
  }
);

TocSection.displayName = 'TocSection';

// packages/vue/src/components/Section.vue
<template>
  <div :ref="setRef">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { inject, onBeforeUnmount, onMounted, ref } from 'vue';
import type { TocContext, TocSectionData } from '../types';

const props = defineProps<{
  id: string;
  level?: number;
  parentId?: string | null;
}>();

const toc = inject<TocContext>('toc');
if (!toc) throw new Error('Section must be used within Toc component');

const { registerSection, unregisterSection } = toc;

const section: TocSectionData = {
  id: props.id,
  level: props.level ?? 0,
  parentId: props.parentId ?? null,
};

const elementRef = ref<HTMLElement | null>(null);

const setRef = (el: HTMLElement | null) => {
  elementRef.value = el;
};

onMounted(() => {
  registerSection(section);
});

onBeforeUnmount(() => {
  unregisterSection(section.id);
});
</script>
